### PR TITLE
Add support of SDF file

### PR DESCRIPTION
**Pull request by FanwangM**
The version number is also handled with `version.py`. A `.gitignore` is also added.
Any suggestions will be appreciated.

### CODE REVIEW

**Comment by tjkessler** [comment]
Hi @fwmeng88,

These look like some great additions! A few notes:

1. The version update for this release will be 0.1.11, please update the new version-related functions accordingly
2. Please add some documentation to the repo's README illustrating how to use the new SDF function
3. Please add a unit test for the new SDF function, making sure to test its functionality in full

Once we get these items squared away we can move ahead with the merge!

Thanks,
Travis

**Comment by FanwangM** [comment]
Thanks for following up! I have fixed all the problems. @tjkessler 

Can you help merge this and make a new release? I have another package that uses the new functionality from `padelpy`. This can help avoid using `submodule`, which is not very friendly to users.

**Comment by tjkessler** [comment]
@fwmeng88,

Nice work, thanks for those edits! I'll go ahead and merge, create a release on GitHub, and publish the release to PyPI!

-Travis

**Comment by FanwangM** [comment]
Thanks! @tjkessler

**Pull request merged**
